// SPDX-License-Identifier: MIT
pragma solidity 0.8.35;

import {Test} from "forge-std/Test.sol";
import {TestToken} from "../src/TestToken.sol";
import {MerkleAirdrop} from "../src/MerkleAirdrop.sol";

/// @notice Root/proofs below were generated by merkle/generate-merkle-tree.mjs
/// against merkle/eligibility.json (the first two entries) and pasted in as
/// fixed constants — see plan step "Build order" #4.
contract MerkleAirdropTest is Test {
    TestToken token;
    MerkleAirdrop airdrop;

    bytes32 constant ROOT = 0x248824d195e54861a7ef96339bedc9acd06783ef2b50e609fd89d7b3ad672ca6;

    address constant ACCOUNT_A = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
    uint256 constant AMOUNT_A = 100000000000000000000;

    address constant ACCOUNT_B = 0x70997970C51812dc3A010C7d01b50e0d17dc79C8;
    uint256 constant AMOUNT_B = 50000000000000000000;

    function proofA() internal pure returns (bytes32[] memory proof) {
        proof = new bytes32[](3);
        proof[0] = 0x723095271a15427e67915b3819d9d45d98df25991da05122fbecaedd6c5ba3c5;
        proof[1] = 0xc7857d518bb9532c702572fed44636b5dd40cce73936fc5c1c8e6c3779f0c41d;
        proof[2] = 0x631c535c3fa6b0f1249c169d29d9948aa2ec63ace76f8741aa521aca9cb23666;
    }

    function proofB() internal pure returns (bytes32[] memory proof) {
        proof = new bytes32[](2);
        proof[0] = 0x9e9863c6fa5d32f9116da49891a1123e03ff838a2a71873fba03c27830e5d102;
        proof[1] = 0x73e98a46eb9999c9340cc2568a066bbfeb392313f40f86d813e3fc369ec08b20;
    }

    function setUp() public {
        token = new TestToken("Airdrop Test Token", "ATT", 1_000_000e18);
        airdrop = new MerkleAirdrop(address(token), ROOT);
        token.transfer(address(airdrop), 265_000000000000000000); // fund with tokenTotal
    }

    function test_ValidClaim_TransfersCorrectAmount() public {
        vm.expectEmit(true, false, false, true, address(airdrop));
        emit MerkleAirdrop.Claimed(ACCOUNT_A, AMOUNT_A);

        airdrop.claim(ACCOUNT_A, AMOUNT_A, proofA());

        assertEq(token.balanceOf(ACCOUNT_A), AMOUNT_A);
        assertEq(token.balanceOf(address(airdrop)), 265_000000000000000000 - AMOUNT_A);
    }

    function test_ValidClaim_SetsHasClaimed() public {
        airdrop.claim(ACCOUNT_A, AMOUNT_A, proofA());
        assertTrue(airdrop.hasClaimed(ACCOUNT_A));
    }

    function test_AnyoneCanSubmitClaimOnBehalfOfEligibleAccount() public {
        // caller (this test contract) is not ACCOUNT_B, but ACCOUNT_B still receives funds
        vm.prank(address(0xdeadbeef));
        airdrop.claim(ACCOUNT_B, AMOUNT_B, proofB());
        assertEq(token.balanceOf(ACCOUNT_B), AMOUNT_B);
    }

    function test_RevertWhen_ProofInvalid() public {
        bytes32[] memory badProof = proofA();
        badProof[0] = bytes32(uint256(badProof[0]) ^ 1); // flip a bit

        vm.expectRevert(MerkleAirdrop.InvalidProof.selector);
        airdrop.claim(ACCOUNT_A, AMOUNT_A, badProof);
    }

    function test_RevertWhen_DoubleClaim() public {
        airdrop.claim(ACCOUNT_A, AMOUNT_A, proofA());

        vm.expectRevert(MerkleAirdrop.AlreadyClaimed.selector);
        airdrop.claim(ACCOUNT_A, AMOUNT_A, proofA());
    }

    function test_RevertWhen_WrongAmount() public {
        vm.expectRevert(MerkleAirdrop.InvalidProof.selector);
        airdrop.claim(ACCOUNT_A, AMOUNT_A * 2, proofA());
    }

    function test_RevertWhen_WrongAccountUsesAnothersProof() public {
        // ACCOUNT_B's proof/amount, but claiming for ACCOUNT_A
        vm.expectRevert(MerkleAirdrop.InvalidProof.selector);
        airdrop.claim(ACCOUNT_A, AMOUNT_B, proofB());
    }

    function testFuzz_ClaimRevertsForRandomInvalidProof(bytes32[3] memory fakeProofFixed) public {
        bytes32[] memory fakeProof = new bytes32[](3);
        fakeProof[0] = fakeProofFixed[0];
        fakeProof[1] = fakeProofFixed[1];
        fakeProof[2] = fakeProofFixed[2];

        vm.expectRevert(MerkleAirdrop.InvalidProof.selector);
        airdrop.claim(ACCOUNT_A, AMOUNT_A, fakeProof);
    }
}
