// SPDX-License-Identifier: MIT
pragma solidity 0.8.35;

import {Script, console} from "forge-std/Script.sol";
import {MerkleAirdrop} from "../src/MerkleAirdrop.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/// @notice Deploys MerkleAirdrop against the root generated by
/// merkle/generate-merkle-tree.mjs, then funds it with the full airdrop
/// amount so claims don't revert for lack of balance (an easy step to forget).
contract DeployAirdrop is Script {
    using SafeERC20 for IERC20;

    function run() external returns (MerkleAirdrop) {
        address tokenAddr = vm.envAddress("TOKEN_ADDRESS");
        uint256 pk = vm.envUint("PRIVATE_KEY");

        string memory json = vm.readFile("merkle/output/merkle-root.json");
        bytes32 root = vm.parseJsonBytes32(json, ".root");
        uint256 tokenTotal = vm.parseJsonUint(json, ".tokenTotal");

        vm.startBroadcast(pk);
        MerkleAirdrop airdrop = new MerkleAirdrop(tokenAddr, root);
        IERC20(tokenAddr).safeTransfer(address(airdrop), tokenTotal);
        vm.stopBroadcast();

        console.log("MerkleAirdrop deployed at:", address(airdrop));
        console.log("Funded with tokenTotal:", tokenTotal);
        return airdrop;
    }
}
